---
- include: desp.yml
- name : Copy platziverse-mqtt
  copy:
      src=platziverse-mqtt
      dest=/usr/local/src
      mode=u=rwx,g=rwx,o=rx
- name: Run npm install
  command: npm install
    chdir=/usr/local/src/platziverse-mqtt
    creates=/usr/local/src/platziverse-mqtt/node_modules
- name:  Run npm start
  command: Intall Systemd script
    src=platziverse-mqtt.services
    dest=/lib/systemd/system
-name: Start platziverse-mqtt
    name=platziverse-mqtt
    state=restarted
    enabled=yes
    