---
- include: deps.yml
- name : Copy platziverse-config
  copy:
      src=platziverse-config
      dest=/usr/local/src
      mode=u=rwx,g=rwx,o=rx
- name: Run npm install
  command: npm install
    chdir=/usr/local/src/platziverse-config
    creates=/usr/local/src/platziverse-config/node_modules

